# Generated by Django 3.2.9 on 2021-11-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
