# Generated by Django 3.2.9 on 2021-11-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_remove_category_depth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
