# Generated by Django 3.2.9 on 2021-11-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_auto_20211106_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='similar_category',
        ),
        migrations.AddField(
            model_name='category',
            name='similar_categories',
            field=models.ManyToManyField(blank=True, related_name='_categories_category_similar_categories_+', to='categories.Category'),
        ),
    ]
